{{- if .Values.watchNamespaces }}
{{- range $ns := .Values.watchNamespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $.Release.Name }}
  namespace: {{ $ns }}
  labels:
    {{- include "balerix-operator.labels" $ | nindent 4 }}
rules:
  {{- include "balerix-operator.rules" $ | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $.Release.Name }}
  namespace: {{ $ns }}
  labels:
    {{- include "balerix-operator.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $.Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ $.Release.Name }}
    namespace: {{ $.Release.Namespace }}
{{- end }}
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ printf "%s-%s" .Release.Namespace .Release.Name }}
  labels:
    {{- include "balerix-operator.labels" . | nindent 4 }}
rules:
  {{- include "balerix-operator.rules" . | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s-%s" .Release.Namespace .Release.Name }}
  labels:
    {{- include "balerix-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ printf "%s-%s" .Release.Namespace .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
{{- end }}
