//! The generated nono profile (Phase 2 spec §4.2 step 4, P2-5, P2-7).

use std::collections::BTreeMap;
use std::path::{Component, Path, PathBuf};

use balerix_core::{AgentId, MaterializeError};
use serde_json::{Value, json};

use crate::fsutil::write_atomic;
use crate::launch::outer_path;
use crate::layout::{AgentPaths, CrewPaths, StateLayout};
use crate::tools::{Cmd, ToolPaths};

pub(crate) const SYSTEM_READ: &[&str] = &["/usr", "/lib", "/lib64", "/bin", "/etc"];

/// Paths balerix grants; user grants that overlap these at a different
/// level are rejected.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Grants {
    pub read: Vec<PathBuf>,
    pub allow: Vec<PathBuf>,
}

pub fn balerix_grants(
    id: &AgentId,
    paths: &AgentPaths,
    crew: &CrewPaths,
    layout: &StateLayout,
    balerix: &Path,
    mise: &Path,
) -> Grants {
    let mut read: Vec<PathBuf> = SYSTEM_READ.iter().map(PathBuf::from).collect();
    // Every pool the agent resolves through: crew, fleet, daemon. All
    // read-only — an agent installs into its own `home/` and can never
    // change a binary a crew-mate executes (Spec E, E-2).
    read.extend(layout.agent_pools(id));
    // `MISE_GLOBAL_CONFIG_FILE` points at the agent's generated `mise.toml`,
    // which sits in the agent root — outside every `allow` below. Without
    // this single-file grant the sandboxed `mise exec` cannot read its own
    // config and dies with "Permission denied (os error 13)".
    read.push(paths.mise_toml.clone());
    // The `SessionStart` relay hook runs this binary inside the sandbox
    // (nono 0.75.0 validates and enforces a single-file `read` entry, and
    // `nono run` inside such a profile executes the granted binary).
    read.push(balerix.to_path_buf());
    // `launch.sh` execs `mise exec` inside the sandbox by the path
    // `ToolPaths` discovered. Locally that is `/usr/local/bin/mise`, inside
    // the `/usr` grant; on a GitHub runner mise-action installs it under
    // `$HOME`, which nothing above grants, and every agent died with exit
    // 127 (command not found). Grant the binary itself; the canonical path
    // in case PATH found a symlink, since Landlock rules bind to the file
    // the path resolves to.
    read.push(std::fs::canonicalize(mise).unwrap_or_else(|_| mise.to_path_buf()));
    // Spec N-3: the crew's object cache, read-only. The agent's private
    // clone borrows objects from it through `objects/info/alternates`; a
    // Landlock read rule on the directory covers the tree beneath it. No
    // path under `repo/` is ever in `allow` — that is the isolation between
    // the agents of one crew (docs/THREAT-MODEL.md).
    read.push(crew.cache_objects());
    Grants {
        read,
        allow: vec![paths.home.clone(), paths.workspace.clone()],
    }
}

fn strs(paths: &[PathBuf]) -> Value {
    Value::Array(
        paths
            .iter()
            .map(|p| Value::String(p.display().to_string()))
            .collect(),
    )
}

/// Base profile ⊕ user block, conflicts rejected first.
pub fn render_profile(
    id: &AgentId,
    grants: &Grants,
    daemon_port: u16,
    env: &BTreeMap<String, String>,
    user: &Value,
) -> Result<Value, MaterializeError> {
    check_conflicts(id, user, grants)?;
    let base = json!({
        "meta": { "name": format!("balerix-{}-{}-{}", id.fleet, id.crew, id.agent), "description": format!("generated by balerix for {id}") },
        "filesystem": { "read": strs(&grants.read), "allow": strs(&grants.allow) },
        "workdir": { "access": "none" },
        // Loopback to the daemon is always allowed; other network stays at
        // nono's default (allowed) unless the user's `sandbox.network`
        // tightens it (architecture spec: "unrestricted by default").
        // `open_port` is the right primitive: it grants localhost TCP on
        // that port and nothing else. `connect_port` would not do — on
        // Landlock it turns outbound TCP into an allowlist, so an agent
        // could reach the daemon and nothing else, not even DNS or the
        // Anthropic API (probed 2026-09-06 with nono 0.75.0). `open_port`
        // also survives a user `block: true`, so hooks keep flowing when
        // egress is cut off.
        "network": { "open_port": [daemon_port] },
        "environment": { "deny_vars": ["*"], "set_vars": env },
        // Written, not left to nono's default: the agent supervisor sits
        // outside the sandbox as the same user, and an agent that could
        // signal it would orphan its own tree out of `stop`'s reach
        // (Spec N amendment §13.6, #118). The top-level key beats a
        // profile the user block `extends`, but nono applies the parent's
        // `platform_overrides` for the running OS after that, so the
        // per-OS patches pin it too. The key is refused in the user block
        // at both levels (`check_conflicts`).
        "security": { "signal_mode": "isolated" },
        "platform_overrides": {
            "linux": { "security": { "signal_mode": "isolated" } },
            "macos": { "security": { "signal_mode": "isolated" } },
        },
    });
    Ok(merge_profile(base, user))
}

/// The profile the daemon's own git runs under in an agent's existing
/// clone: the harvest's `upload-pack` and the probes around it (Spec N
/// amendment 2026-10-01 §4, #68, #70). The daemon reads every repository
/// its uid can; the agent reads its own clone and the crew cache. Under
/// this profile git reads exactly those two (plus the empty hooks
/// directory, its own binary and its exec-path), writes nothing and
/// has no network, so
/// a clone pointed at another repository serves nothing the agent could
/// not already read, and a promisor remote fetches nothing on any git.
///
/// Not derived from the agent's profile: that one carries write access,
/// open network, the user's `sandbox` block and the agent's `env`, none
/// of which the daemon's git should have. `set_vars` holds the hardening
/// for git's environment, since nono drops every variable this list does
/// not name. `git` comes from the host:
/// the binary is granted as a single file, canonical since Landlock rules
/// bind to what the path resolves to, and `exec_path` (`git_exec_path`)
/// as a directory, since `upload-pack` spawns `pack-objects` through it
/// (#109). Its libraries are not granted: a git that loads them from
/// outside `SYSTEM_READ` (nix, Linuxbrew), or a mise shim, cannot run
/// under this profile and the calls fail closed (Spec N amendment §12.1,
/// NS-6) unless the operator names their prefix in the daemon's
/// `[sandbox] git_read` (#111), which `git_read` carries.
pub fn render_git_profile(
    id: &AgentId,
    paths: &AgentPaths,
    crew: &CrewPaths,
    git: &Path,
    exec_path: &Path,
    git_read: &[PathBuf],
) -> Value {
    let mut read: Vec<PathBuf> = SYSTEM_READ.iter().map(PathBuf::from).collect();
    read.push(std::fs::canonicalize(git).unwrap_or_else(|_| git.to_path_buf()));
    read.push(exec_path.to_path_buf());
    // the daemon's `[sandbox] git_read` (config.toml, #111): read-only
    // prefixes a git built outside the system prefixes loads its libraries
    // from; validated at load, never from a fleet's `sandbox` block
    read.extend(git_read.iter().cloned());
    read.push(crew.cache_objects());
    read.push(crew.no_hooks());
    read.push(paths.workspace.clone());
    // git only honours a ceiling that matches the resolved path
    let ceiling = paths
        .root
        .canonicalize()
        .unwrap_or_else(|_| paths.root.clone());
    json!({
        "meta": {
            "name": format!("balerix-git-{}-{}-{}", id.fleet, id.crew, id.agent),
            "description": format!("generated by balerix for its own git in {id}'s clone"),
        },
        "filesystem": { "read": strs(&read) },
        "workdir": { "access": "none" },
        "network": { "block": true },
        "environment": {
            "deny_vars": ["*"],
            "set_vars": {
                "GIT_OPTIONAL_LOCKS": "0",
                "GIT_NO_LAZY_FETCH": "1",
                "GIT_TERMINAL_PROMPT": "0",
                "GIT_CONFIG_NOSYSTEM": "1",
                "GIT_CEILING_DIRECTORIES": ceiling.display().to_string(),
            },
        },
    })
}

/// The directory the host git runs its helpers from, resolved. Asked of
/// git itself, unsandboxed: it names no repository and reads nothing the
/// agent wrote. From an empty environment but `PATH`, as the sandboxed
/// call starts: a `GIT_EXEC_PATH` the daemon inherited would make the
/// grant name a directory the sandboxed git never uses. A git that
/// cannot answer, or names something that is not a directory, fails the
/// step: no profile is written without the grant.
fn git_exec_path(tools: &ToolPaths, id: &str) -> Result<PathBuf, MaterializeError> {
    let tool_error = |stderr: String| MaterializeError::Tool {
        id: id.to_string(),
        tool: "git".into(),
        subcommand: "--exec-path".into(),
        args: vec!["--exec-path".into()],
        stderr,
    };
    let out = Cmd::new(&tools.git)
        .env_clear()
        .env("PATH", outer_path(tools))
        .args(["--exec-path"])
        .run()
        .map_err(|f| tool_error(f.stderr))?;
    let named = PathBuf::from(out.stdout.trim_end_matches(['\r', '\n']));
    let dir = std::fs::canonicalize(&named)
        .map_err(|e| tool_error(format!("{}: {e}", named.display())))?;
    if !dir.is_dir() {
        return Err(tool_error(format!("{}: not a directory", named.display())));
    }
    Ok(dir)
}

/// Writes the git profile just before the daemon uses it, so nothing
/// depends on the order of the materialize steps or on a file an earlier
/// pass (or anything else) left there. Validated only when the bytes
/// changed. Sweeps the temp nono homes another, killed, daemon left
/// (`workspace::sweep_stale_homes`). Creates what nono needs to exist: the hooks directory the
/// profile names, nono's `$HOME` and the log directory.
pub fn write_git_profile(
    tools: &ToolPaths,
    id: &str,
    paths: &AgentPaths,
    crew: &CrewPaths,
    git_read: &[PathBuf],
) -> Result<(), MaterializeError> {
    let agent_id: AgentId = id.parse().map_err(|_| MaterializeError::Invalid {
        id: id.to_string(),
        message: "not an agent id".into(),
    })?;
    for dir in [crew.no_hooks(), paths.nono_home.clone(), paths.logs.clone()] {
        std::fs::create_dir_all(&dir).map_err(|e| MaterializeError::Io {
            id: id.to_string(),
            path: dir.clone(),
            message: e.to_string(),
        })?;
    }
    // the temp nono homes a SIGKILLed daemon could not remove
    crate::workspace::sweep_stale_homes(paths);
    let exec_path = git_exec_path(tools, id)?;
    let profile = render_git_profile(&agent_id, paths, crew, &tools.git, &exec_path, git_read);
    let path = paths.git_profile.clone();
    if write_profile_at(&agent_id, &path, &profile)? {
        // nono's state stays out of the agent's own `nono/` (#108)
        let home = crate::workspace::ScratchHome::new(paths).map_err(|e| MaterializeError::Io {
            id: id.to_string(),
            path: paths.nono_home.clone(),
            message: format!("cannot create nono's home beside it: {e}"),
        })?;
        validate_profile_at(
            tools,
            &agent_id,
            &path,
            home.path(),
            &paths.logs.join("nono.validate.log"),
        )?;
    }
    Ok(())
}

/// nono's `extends` rules: arrays append and dedupe, maps recurse, scalars
/// user-wins.
pub fn merge_profile(base: Value, user: &Value) -> Value {
    match (base, user) {
        (Value::Object(mut b), Value::Object(u)) => {
            for (k, v) in u {
                let merged = match b.remove(k) {
                    Some(existing) => merge_profile(existing, v),
                    None => v.clone(),
                };
                b.insert(k.clone(), merged);
            }
            Value::Object(b)
        }
        (Value::Array(mut b), Value::Array(u)) => {
            for v in u {
                if !b.contains(v) {
                    b.push(v.clone());
                }
            }
            Value::Array(b)
        }
        (_, u) => u.clone(),
    }
}

/// Access level of a grant list key.
fn level(key: &str) -> Option<&'static str> {
    match key {
        "read" | "read_file" => Some("read"),
        "allow" | "allow_file" => Some("allow"),
        "write" | "write_file" => Some("write"),
        _ => None,
    }
}

fn overlaps(a: &Path, b: &Path) -> bool {
    a == b || a.starts_with(b) || b.starts_with(a)
}

fn entry_path(v: &Value) -> Option<PathBuf> {
    match v {
        Value::String(s) => Some(PathBuf::from(s)),
        Value::Object(m) => m.get("path").and_then(Value::as_str).map(PathBuf::from),
        _ => None,
    }
}

pub fn check_conflicts(
    id: &AgentId,
    user: &Value,
    grants: &Grants,
) -> Result<(), MaterializeError> {
    let conflict = |path: String, message: String| MaterializeError::SandboxConflict {
        id: id.to_string(),
        path,
        message,
    };
    let Value::Object(u) = user else {
        return Ok(());
    };
    if u.contains_key("environment") {
        return Err(conflict(
            "environment".into(),
            "balerix-owned; set variables through `env` instead".into(),
        ));
    }
    if u.contains_key("meta") {
        return Err(conflict("meta".into(), "balerix-owned".into()));
    }
    check_security(u, "", &conflict)?;
    if let Some(overrides) = u.get("platform_overrides") {
        let Value::Object(os) = overrides else {
            return Err(conflict(
                "platform_overrides".into(),
                "expected an object".into(),
            ));
        };
        // nono applies the patch for the running OS after `extends`, so
        // it could loosen what the base profile pins
        for (name, patch) in os {
            if let Value::Object(patch) = patch {
                check_security(patch, &format!("platform_overrides.{name}."), &conflict)?;
            }
        }
    }
    let Some(fs_value) = u.get("filesystem") else {
        return Ok(());
    };
    let Value::Object(fs) = fs_value else {
        return Err(conflict("filesystem".into(), "expected an object".into()));
    };
    for (key, entries) in fs {
        let Some(user_level) = level(key) else {
            continue;
        };
        let Value::Array(items) = entries else {
            return Err(conflict(
                format!("filesystem.{key}"),
                "expected an array".into(),
            ));
        };
        for (i, item) in items.iter().enumerate() {
            let Some(p) = entry_path(item) else {
                continue;
            };
            let hits = grants
                .read
                .iter()
                .map(|g| (g, "read"))
                .chain(grants.allow.iter().map(|g| (g, "allow")));
            for (g, balerix_level) in hits {
                if overlaps(&p, g) && balerix_level != user_level {
                    return Err(conflict(
                        format!("filesystem.{key}[{i}]"),
                        format!(
                            "{} overlaps balerix {balerix_level} path {}",
                            p.display(),
                            g.display()
                        ),
                    ));
                }
            }
        }
    }
    Ok(())
}

/// `security.signal_mode` is balerix's (#118), whatever its value: even
/// `null` hands the decision to whatever profile `extends` names. The rest
/// of `security` is the user's.
fn check_security(
    block: &serde_json::Map<String, Value>,
    prefix: &str,
    conflict: &impl Fn(String, String) -> MaterializeError,
) -> Result<(), MaterializeError> {
    let Some(security) = block.get("security") else {
        return Ok(());
    };
    let Value::Object(security) = security else {
        return Err(conflict(
            format!("{prefix}security"),
            "expected an object".into(),
        ));
    };
    if security.contains_key("signal_mode") {
        return Err(conflict(
            format!("{prefix}security.signal_mode"),
            "balerix-owned; agents stay signal-isolated".into(),
        ));
    }
    Ok(())
}

/// balerix's own trees, named for the error message: the state, data and
/// config roots (`StateLayout`).
pub type Roots<'a> = [(&'a str, &'a Path)];

/// The grants balerix already gives a plugin under its roots, by access:
/// a manifest entry inside one of them is not a reach into the roots.
#[derive(Debug, Clone, Copy)]
pub struct PluginGrants<'a> {
    /// Read-only: the package and the mise pool. Only a `read` or
    /// `read_file` entry is let through here.
    pub read_only: &'a [PathBuf],
    /// Read-write: `home/` and `scratch/`. Any level.
    pub read_write: &'a [PathBuf],
}

/// What a plugin's `sandbox` block may set (#2). Everything else nono
/// accepts reaches past the filesystem rules below: `extends`,
/// `groups`, `packs`, `command_policies` (with its own `fs_read`),
/// `workdir`, `hooks` and `session_hooks` (run outside the sandbox),
/// credential capture and injection, raw Seatbelt rules, AF_UNIX socket
/// grants, process inspection and capability elevation (nono 0.79.0's
/// profile schema). The top level takes `filesystem`, `network`,
/// `security` and `platform_overrides`; each patch the first three.
/// `platform_overrides` names nono knows.
const PLUGIN_OSES: &[&str] = &["linux", "macos", "windows"];
/// Grant lists, checked against the roots, and `deny`, which grants
/// nothing (checked as a literal path only). Not `bypass_protection`: on
/// macOS it lifts nono's `deny_credentials` for `~/.ssh` and `~/.aws`.
const PLUGIN_FS_KEYS: &[&str] = &[
    "read",
    "read_file",
    "allow",
    "allow_file",
    "write",
    "write_file",
    "deny",
];
/// Ports, domains and proxies; never credentials (`credentials`,
/// `custom_credentials` make nono's supervisor read a secret — a
/// `file://` or `env://` one included — and hand it to an upstream the
/// manifest names) nor TLS interception.
const PLUGIN_NETWORK_KEYS: &[&str] = &[
    "block",
    "allow_http2",
    "network_profile",
    "allow_domain",
    "deny_domain",
    "open_port",
    "open_port_range",
    "connect_port",
    "listen_port",
    "listen_port_range",
    "no_proxy",
    "upstream_proxy",
    "upstream_bypass",
];
/// `signal_mode` is refused by `check_conflicts` (#118); the rest of
/// `security` would widen the sandbox at runtime (`process_info_mode`
/// reads other processes, among them other plugins' tokens in their
/// environment; `capability_elevation` with `approval_backends` lets a
/// webhook grant paths) or degrade it (`wsl2_proxy_policy`).
const PLUGIN_SECURITY_KEYS: &[&str] = &["ipc_mode", "signal_mode"];

/// A plugin manifest's `sandbox` block (#2): only the keys above, and no
/// filesystem grant that reaches balerix's own state, data or config —
/// the daemon's token and vault, the fleet store, other plugins' trees
/// and KV, every agent. Every path entry (top level and in
/// `platform_overrides.<os>`) must be an absolute, literal path: no `~`,
/// no `$`, no `..` and no glob (`*`, `?`, `[`, `{`), since nono would
/// expand what balerix compares. A grant must not overlap a root in
/// either direction, so `/` or the home holding the roots is refused as
/// well, unless it lies inside a grant balerix already gives the plugin
/// at that level (`grants`). The plugin's own `plugins/<name>/` is not
/// one: `kv/` is reached through the API only. Both the path as written
/// and as resolved (the longest existing prefix canonicalised, a
/// dangling link followed) are compared, so a symlink into a root is
/// caught; an entry is let through only if its resolved path is inside a
/// resolved grant. Run on every render, so a symlink planted since the
/// last one is seen; one planted between the render and nono's start
/// (Landlock follows it then) is not, a gap the install-time trust in
/// the package already covers. `security.signal_mode`, `environment` and `meta` are
/// left to `check_conflicts`, which refuses them with their own messages.
pub fn check_plugin_sandbox(
    id: &AgentId,
    user: &Value,
    roots: &Roots<'_>,
    grants: PluginGrants<'_>,
) -> Result<(), MaterializeError> {
    let conflict = |path: String, message: String| MaterializeError::SandboxConflict {
        id: id.to_string(),
        path,
        message,
    };
    let Value::Object(u) = user else {
        return Ok(());
    };
    let roots: Vec<(&str, [PathBuf; 2])> = roots
        .iter()
        .map(|(what, p)| (*what, [p.to_path_buf(), resolve_existing(p)]))
        .collect();
    let resolve = |ps: &[PathBuf]| ps.iter().map(|p| resolve_existing(p)).collect::<Vec<_>>();
    let read_only = resolve(grants.read_only);
    let read_write = resolve(grants.read_write);
    let ctx = PluginCheck {
        roots: &roots,
        read_only: &read_only,
        read_write: &read_write,
    };
    ctx.block(u, "", true).map_err(|(at, m)| conflict(at, m))
}

struct PluginCheck<'a> {
    roots: &'a [(&'a str, [PathBuf; 2])],
    read_only: &'a [PathBuf],
    read_write: &'a [PathBuf],
}

type Refusal = (String, String);

fn not_accepted(at: String) -> Refusal {
    (at, "not accepted in a plugin's sandbox block".into())
}

fn object<'v>(v: &'v Value, at: &str) -> Result<&'v serde_json::Map<String, Value>, Refusal> {
    v.as_object()
        .ok_or_else(|| (at.to_string(), "expected an object".into()))
}

impl PluginCheck<'_> {
    /// The top level (`top`) or one `platform_overrides.<os>` patch.
    fn block(
        &self,
        u: &serde_json::Map<String, Value>,
        prefix: &str,
        top: bool,
    ) -> Result<(), Refusal> {
        for (key, value) in u {
            let at = format!("{prefix}{key}");
            match key.as_str() {
                // `check_conflicts`' to refuse, with its own message
                "environment" | "meta" if top => {}
                "filesystem" => self.filesystem(object(value, &at)?, &at)?,
                "network" => {
                    for k in object(value, &at)?.keys() {
                        if !PLUGIN_NETWORK_KEYS.contains(&k.as_str()) {
                            return Err(not_accepted(format!("{at}.{k}")));
                        }
                    }
                }
                "security" => {
                    for k in object(value, &at)?.keys() {
                        if !PLUGIN_SECURITY_KEYS.contains(&k.as_str()) {
                            return Err(not_accepted(format!("{at}.{k}")));
                        }
                    }
                }
                "platform_overrides" if top => {
                    for (os, patch) in object(value, &at)? {
                        let os_at = format!("{at}.{os}");
                        if !PLUGIN_OSES.contains(&os.as_str()) {
                            return Err(not_accepted(os_at));
                        }
                        self.block(object(patch, &os_at)?, &format!("{os_at}."), false)?;
                    }
                }
                _ => return Err(not_accepted(at)),
            }
        }
        Ok(())
    }

    fn filesystem(&self, fs: &serde_json::Map<String, Value>, at: &str) -> Result<(), Refusal> {
        for (key, entries) in fs {
            let list_at = format!("{at}.{key}");
            if !PLUGIN_FS_KEYS.contains(&key.as_str()) {
                return Err(not_accepted(list_at));
            }
            let Value::Array(items) = entries else {
                return Err((list_at, "expected an array".into()));
            };
            for (i, item) in items.iter().enumerate() {
                let entry_at = format!("{list_at}[{i}]");
                let raw = entry_text(item).ok_or_else(|| {
                    (
                        entry_at.clone(),
                        "expected a path string or { path, when }".to_string(),
                    )
                })?;
                let path = literal_path(raw).map_err(|m| (entry_at.clone(), m))?;
                if let Some(level) = level(key) {
                    self.grant(raw, &path, level).map_err(|m| (entry_at, m))?;
                }
            }
        }
        Ok(())
    }

    /// One grant against the roots; the message on refusal.
    fn grant(&self, raw: &str, path: &Path, level: &str) -> Result<(), String> {
        let resolved = resolve_existing(path);
        let forms = [path.to_path_buf(), resolved.clone()];
        let inside = |gs: &[PathBuf]| gs.iter().any(|g| resolved.starts_with(g));
        let granted = inside(self.read_write) || (level == "read" && inside(self.read_only));
        for (what, root_forms) in self.roots {
            for root in root_forms {
                for entry in &forms {
                    if root.starts_with(entry) {
                        return Err(format!(
                            "{raw} covers balerix's {what} root {}",
                            root.display()
                        ));
                    }
                    if entry.starts_with(root) && !granted {
                        return Err(format!(
                            "{raw} is inside balerix's {what} root {}; a plugin may name \
                             only paths in its home/ or scratch/ there, or read its \
                             package or the mise pool",
                            root.display()
                        ));
                    }
                }
            }
        }
        Ok(())
    }
}

/// The path of a nono `ConditionalPath`: a string, or an object with a
/// string `path` and at most a `when` beside it. Anything else is refused
/// here rather than left to nono's validation.
fn entry_text(v: &Value) -> Option<&str> {
    match v {
        Value::String(s) => Some(s),
        Value::Object(m) if m.keys().all(|k| k == "path" || k == "when") => {
            m.get("path").and_then(Value::as_str)
        }
        _ => None,
    }
}

/// An entry nono will not expand: absolute, no `~`, `$`, `..` or glob.
fn literal_path(raw: &str) -> Result<PathBuf, String> {
    if raw.starts_with('~') {
        return Err(format!("{raw}: `~` is not expanded; name an absolute path"));
    }
    if raw.contains('$') {
        return Err(format!(
            "{raw}: variables are not expanded; name an absolute path"
        ));
    }
    if raw.contains(['*', '?', '[', '{']) {
        return Err(format!(
            "{raw}: glob patterns (`*`, `?`, `[`, `{{`) are not accepted; name a literal path"
        ));
    }
    let path = Path::new(raw);
    if !path.is_absolute() {
        return Err(format!("{raw}: must be an absolute path"));
    }
    if path.components().any(|c| c == Component::ParentDir) {
        return Err(format!("{raw}: must not contain `..`"));
    }
    Ok(path.to_path_buf())
}

/// `path` with its longest existing prefix canonicalised and the rest
/// appended: what a symlink on the way actually names, for a path that
/// may not exist yet. A dangling symlink on the way is followed to its
/// target (up to 40 links, as the kernel does). Unchanged when nothing of
/// it exists.
fn resolve_existing(path: &Path) -> PathBuf {
    resolve_links(path, 40)
}

fn resolve_links(path: &Path, links: u32) -> PathBuf {
    let mut existing = path;
    let mut rest = Vec::new();
    loop {
        let finish = |base: PathBuf| rest.iter().rev().fold(base, |acc, part| acc.join(part));
        if let Ok(canon) = std::fs::canonicalize(existing) {
            return finish(canon);
        }
        if links > 0
            && let Ok(target) = std::fs::read_link(existing)
            && let Some(parent) = existing.parent()
        {
            let base = std::fs::canonicalize(parent).unwrap_or_else(|_| parent.to_path_buf());
            return resolve_links(&finish(lexical(&base.join(target))), links - 1);
        }
        match (existing.parent(), existing.file_name()) {
            (Some(parent), Some(name)) => {
                rest.push(name);
                existing = parent;
            }
            _ => return path.to_path_buf(),
        }
    }
}

/// `..` and `.` folded away without touching the filesystem: for a link
/// target joined onto its canonical directory.
fn lexical(path: &Path) -> PathBuf {
    let mut out = PathBuf::new();
    for c in path.components() {
        match c {
            Component::ParentDir => {
                out.pop();
            }
            Component::CurDir => {}
            other => out.push(other),
        }
    }
    out
}

/// Writes the profile; returns whether its bytes changed.
pub fn write_profile_at(
    id: &AgentId,
    path: &Path,
    profile: &Value,
) -> Result<bool, MaterializeError> {
    let bytes = serde_json::to_vec_pretty(profile).unwrap_or_default();
    if std::fs::read(path).ok().as_deref() == Some(bytes.as_slice()) {
        return Ok(false);
    }
    // 0600: the profile is the sandbox's boundary, and a writable or
    // widely readable one is a map of every path the agent may reach.
    write_atomic(path, &bytes, 0o600).map_err(|e| MaterializeError::Io {
        id: id.to_string(),
        path: path.to_path_buf(),
        message: e.to_string(),
    })?;
    Ok(true)
}

pub fn write_profile(
    id: &AgentId,
    paths: &AgentPaths,
    profile: &Value,
) -> Result<bool, MaterializeError> {
    write_profile_at(id, &paths.profile, profile)
}

pub fn validate_profile_at(
    tools: &ToolPaths,
    id: &AgentId,
    profile: &Path,
    nono_home: &Path,
    log: &Path,
) -> Result<(), MaterializeError> {
    Cmd::new(&tools.nono)
        .args(["-s", "profile", "validate", &profile.display().to_string()])
        .env("HOME", nono_home.display().to_string())
        .log(log)
        .run()
        .map(|_| ())
        .map_err(|f| MaterializeError::Tool {
            id: id.to_string(),
            tool: f.tool,
            subcommand: "profile validate".into(),
            args: f.args,
            stderr: if f.stderr.trim().is_empty() {
                "profile invalid".into()
            } else {
                f.stderr
            },
        })
}

pub fn validate_profile(
    tools: &ToolPaths,
    id: &AgentId,
    paths: &AgentPaths,
) -> Result<(), MaterializeError> {
    validate_profile_at(
        tools,
        id,
        &paths.profile,
        &paths.nono_home,
        &paths.logs.join("nono.validate.log"),
    )
}

/// Spec O §6.2 step 2: `nono -s run --profile <profile> -- /bin/true` in
/// the sidecar's own container, which shares the pod's seccomp settings
/// and the node's kernel with the agent container. nono's own exit 1 with
/// `Landlock not available` is the `SandboxUnavailable` signal (§19.2);
/// `/sys/kernel/security/lsm` is not mounted in a pod, so there is nothing
/// else to read.
pub fn sandbox_self_test(tools: &ToolPaths, paths: &AgentPaths) -> Result<(), SelfTestError> {
    let out = std::process::Command::new(&tools.nono)
        .args(["-s", "run", "--profile"])
        .arg(&paths.profile)
        .args(["--", "/bin/true"])
        .env_clear()
        .env("HOME", &paths.nono_home)
        .env("PATH", "/usr/local/bin:/usr/bin:/bin")
        .output()
        .map_err(|e| SelfTestError::Io(e.to_string()))?;
    if out.status.success() {
        return Ok(());
    }
    let stderr = String::from_utf8_lossy(&out.stderr);
    let line = stderr.lines().next().unwrap_or("").trim().to_string();
    if out.status.code() == Some(1) && line.contains("Landlock not available") {
        return Err(SelfTestError::Unavailable(line));
    }
    Err(SelfTestError::Failed(line))
}

/// The Landlock ABI that scopes signals (Linux 6.12). Below it nono
/// cannot enforce `signal_mode: isolated` (#118).
pub const SIGNAL_SCOPING_ABI: u32 = 6;

/// The ABI `nono setup --check-only` reports on its `Landlock V<n>` line;
/// `None` when no such line is there.
pub fn landlock_abi(setup_report: &str) -> Option<u32> {
    setup_report.lines().find_map(|line| {
        line.trim()
            .trim_start_matches(['*', ' '])
            .strip_prefix("Landlock V")?
            .trim()
            .parse()
            .ok()
    })
}

/// The start-up warning for a kernel that cannot scope signals, if any.
/// An unknown ABI warns about nothing: the serve start-up never fails on
/// this, and a guess is no better than silence.
pub fn signal_scoping_warning(abi: Option<u32>) -> Option<String> {
    let abi = abi?;
    (abi < SIGNAL_SCOPING_ABI).then(|| {
        format!(
            "Landlock ABI v{abi} cannot scope signals (v{SIGNAL_SCOPING_ABI}, Linux 6.12, can): \
             agents' signal_mode isolated is not enforced, and an agent can signal its \
             supervisor (#118)"
        )
    })
}

/// Asks `nono setup --check-only` for the kernel's Landlock ABI, from an
/// empty environment with `home` as nono's `$HOME`; with its update check
/// off it writes nothing there. `None` when nono cannot be run or does
/// not say.
pub fn host_landlock_abi(tools: &ToolPaths, home: &Path) -> Option<u32> {
    let out = std::process::Command::new(&tools.nono)
        .args(["setup", "--check-only"])
        .env_clear()
        .env("HOME", home)
        .env("PATH", "/usr/local/bin:/usr/bin:/bin")
        .env("NO_COLOR", "1")
        // otherwise it asks update.nono.sh and records that under `home`
        .env("NONO_NO_UPDATE_CHECK", "1")
        .output()
        .ok()?;
    landlock_abi(&String::from_utf8_lossy(&out.stdout))
        .or_else(|| landlock_abi(&String::from_utf8_lossy(&out.stderr)))
}

#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum SelfTestError {
    /// nono exited 1 with `Landlock not available` (Spec O §19.2).
    #[error("SandboxUnavailable: {0}")]
    Unavailable(String),
    /// Any other non-zero exit; the first stderr line.
    #[error("sandbox self-test failed: {0}")]
    Failed(String),
    #[error("sandbox self-test could not run nono: {0}")]
    Io(String),
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fixture() -> (AgentId, Grants, BTreeMap<String, String>) {
        let layout = StateLayout::from_env(Path::new("/h"), |_| None);
        let id: AgentId = "f/c/a".parse().unwrap();
        let paths = layout.agent(&id);
        let crew = layout.crew(&id.crew_ref());
        let grants = balerix_grants(
            &id,
            &paths,
            &crew,
            &layout,
            Path::new("/opt/balerix"),
            Path::new("/opt/mise"),
        );
        (
            id,
            grants,
            BTreeMap::from([("HOME".to_string(), paths.home.display().to_string())]),
        )
    }

    #[test]
    fn base_profile_has_the_required_grants_env_and_port() {
        let (id, grants, env) = fixture();
        let p = render_profile(&id, &grants, 7643, &env, &json!({})).unwrap();
        assert_eq!(p["meta"]["name"], "balerix-f-c-a");
        assert_eq!(p["filesystem"]["read"][0], "/usr");
        assert_eq!(
            p["filesystem"]["read"][5], "/h/.local/state/balerix/fleets/f/crews/c/mise",
            "crew pool"
        );
        assert_eq!(
            p["filesystem"]["read"][6], "/h/.local/state/balerix/fleets/f/mise",
            "fleet pool"
        );
        assert_eq!(
            p["filesystem"]["read"][7], "/h/.local/share/balerix/mise",
            "daemon pool"
        );
        assert_eq!(
            p["filesystem"]["read"][8],
            "/h/.local/state/balerix/fleets/f/crews/c/agents/a/mise.toml"
        );
        assert_eq!(p["filesystem"]["read"][9], "/opt/balerix");
        assert_eq!(
            p["filesystem"]["read"][10], "/opt/mise",
            "mise may live outside /usr (CI installs it under $HOME)"
        );
        assert_eq!(
            p["filesystem"]["read"][11],
            "/h/.local/state/balerix/fleets/f/crews/c/repo/.git/objects",
            "Spec N-3: the crew's object cache, read-only"
        );
        assert_eq!(p["filesystem"]["read"].as_array().unwrap().len(), 12);
        assert_eq!(
            p["filesystem"]["allow"],
            json!([
                "/h/.local/state/balerix/fleets/f/crews/c/agents/a/home",
                "/h/.local/state/balerix/fleets/f/crews/c/agents/a/workspace",
            ]),
            "nothing under crews/c/repo is ever writable (Spec N §6)"
        );
        assert_eq!(p["workdir"]["access"], "none");
        assert_eq!(
            p["security"],
            json!({ "signal_mode": "isolated" }),
            "pinned, not left to nono's default: the supervisor outside must not be signalled (#118)"
        );
        assert_eq!(
            p["platform_overrides"],
            json!({
                "linux": { "security": { "signal_mode": "isolated" } },
                "macos": { "security": { "signal_mode": "isolated" } },
            }),
            "an `extends` parent's per-OS override is applied after the top level"
        );
        assert_eq!(
            p["network"],
            json!({ "open_port": [7643] }),
            "loopback to the daemon only; no connect_port allowlist"
        );
        assert_eq!(p["environment"]["deny_vars"], json!(["*"]));
        assert_eq!(
            p["environment"]["set_vars"]["HOME"],
            "/h/.local/state/balerix/fleets/f/crews/c/agents/a/home"
        );
    }

    #[test]
    fn user_block_merges_with_extends_semantics() {
        let (id, grants, env) = fixture();
        let user = json!({ "network": { "block": true, "open_port": [7643, 8080] }, "filesystem": { "read": ["/opt/data"] }, "extends": "default" });
        let p = render_profile(&id, &grants, 7643, &env, &user).unwrap();
        assert_eq!(p["network"]["block"], true);
        assert_eq!(
            p["network"]["open_port"],
            json!([7643, 8080]),
            "append + dedupe"
        );
        assert_eq!(
            p["filesystem"]["read"].as_array().unwrap().last().unwrap(),
            "/opt/data"
        );
        assert_eq!(p["extends"], "default");
    }

    #[test]
    fn a_user_network_block_keeps_the_daemon_reachable() {
        let (id, grants, env) = fixture();
        let user = json!({ "network": { "block": true } });
        let p = render_profile(&id, &grants, 7643, &env, &user).unwrap();
        assert_eq!(p["network"]["block"], true);
        assert_eq!(
            p["network"]["open_port"],
            json!([7643]),
            "hooks must reach the daemon even when egress is blocked"
        );
        let user = json!({ "network": { "connect_port": [443] } });
        let p = render_profile(&id, &grants, 7643, &env, &user).unwrap();
        assert_eq!(p["network"]["connect_port"], json!([443]));
        assert_eq!(p["network"]["open_port"], json!([7643]));
    }

    #[test]
    fn owned_keys_and_overlapping_grants_are_rejected_with_paths() {
        let (id, grants, env) = fixture();
        let e = render_profile(
            &id,
            &grants,
            1,
            &env,
            &json!({ "environment": { "set_vars": { "X": "1" } } }),
        )
        .unwrap_err();
        assert_eq!(
            e.to_string(),
            "f/c/a: sandbox.environment: balerix-owned; set variables through `env` instead"
        );
        let e = render_profile(
            &id,
            &grants,
            1,
            &env,
            &json!({ "filesystem": { "read": ["/x", "/h/.local/state/balerix/fleets/f/crews/c/agents/a/home/.claude"] } }),
        )
        .unwrap_err();
        assert_eq!(
            e.to_string(),
            "f/c/a: sandbox.filesystem.read[1]: /h/.local/state/balerix/fleets/f/crews/c/agents/a/home/.claude overlaps balerix allow path /h/.local/state/balerix/fleets/f/crews/c/agents/a/home"
        );
        let e = render_profile(
            &id,
            &grants,
            1,
            &env,
            &json!({ "filesystem": { "allow": [{ "path": "/usr/local" }] } }),
        )
        .unwrap_err();
        assert!(e.to_string().contains("overlaps balerix read path /usr"));
        // same level is fine
        assert!(
            render_profile(
                &id,
                &grants,
                1,
                &env,
                &json!({ "filesystem": { "read": ["/usr/share"] } })
            )
            .is_ok()
        );
    }

    /// #118: the agent must not loosen signal isolation, whether at the
    /// top level or through the per-OS patch nono applies after `extends`.
    #[test]
    fn signal_mode_is_balerix_owned_at_every_level() {
        let (id, grants, env) = fixture();
        let refuse = |user: Value| {
            render_profile(&id, &grants, 1, &env, &user)
                .unwrap_err()
                .to_string()
        };
        assert_eq!(
            refuse(json!({ "security": { "signal_mode": "allow_all" } })),
            "f/c/a: sandbox.security.signal_mode: balerix-owned; agents stay signal-isolated"
        );
        assert_eq!(
            refuse(json!({ "security": { "signal_mode": null } })),
            "f/c/a: sandbox.security.signal_mode: balerix-owned; agents stay signal-isolated",
            "null would fall back to whatever `extends` names"
        );
        assert_eq!(
            refuse(
                json!({ "platform_overrides": { "linux": { "security": { "signal_mode": "allow_same_sandbox" } } } })
            ),
            "f/c/a: sandbox.platform_overrides.linux.security.signal_mode: balerix-owned; agents stay signal-isolated"
        );
        assert_eq!(
            refuse(
                json!({ "platform_overrides": { "macos": { "security": { "signal_mode": "allow_all" } } } })
            ),
            "f/c/a: sandbox.platform_overrides.macos.security.signal_mode: balerix-owned; agents stay signal-isolated"
        );
        assert_eq!(
            refuse(json!({ "security": "allow_all" })),
            "f/c/a: sandbox.security: expected an object"
        );
        assert_eq!(
            refuse(json!({ "platform_overrides": { "linux": { "security": null } } })),
            "f/c/a: sandbox.platform_overrides.linux.security: expected an object"
        );
        // the rest of `security` is the user's
        let p = render_profile(
            &id,
            &grants,
            1,
            &env,
            &json!({ "security": { "process_info_mode": "allow_all" } }),
        )
        .unwrap();
        assert_eq!(
            p["security"],
            json!({ "signal_mode": "isolated", "process_info_mode": "allow_all" })
        );
        assert!(
            render_profile(
                &id,
                &grants,
                1,
                &env,
                &json!({ "platform_overrides": { "linux": { "network": { "block": true } } } })
            )
            .is_ok()
        );
    }

    #[test]
    fn malformed_filesystem_shapes_are_rejected() {
        let (id, grants, env) = fixture();
        let e =
            render_profile(&id, &grants, 1, &env, &json!({ "filesystem": "nope" })).unwrap_err();
        assert_eq!(
            e.to_string(),
            "f/c/a: sandbox.filesystem: expected an object"
        );
        let e = render_profile(
            &id,
            &grants,
            1,
            &env,
            &json!({ "filesystem": { "read": "/opt/data" } }),
        )
        .unwrap_err();
        assert_eq!(
            e.to_string(),
            "f/c/a: sandbox.filesystem.read: expected an array"
        );
    }

    #[test]
    fn every_pool_the_agent_resolves_through_is_readable() {
        let layout = StateLayout::from_env(Path::new("/h"), |_| None);
        let id: AgentId = "payments/backend/alice".parse().unwrap();
        let paths = layout.agent(&id);
        let crew = layout.crew(&id.crew_ref());
        let g = balerix_grants(
            &id,
            &paths,
            &crew,
            &layout,
            Path::new("/tools/balerix"),
            Path::new("/tools/mise"),
        );
        for pool in layout.agent_pools(&id) {
            assert!(
                g.read.contains(&pool),
                "{} must be readable inside the sandbox",
                pool.display()
            );
        }
        for pool in layout.agent_pools(&id) {
            assert!(
                !g.allow.contains(&pool),
                "{} must never be writable",
                pool.display()
            );
        }
    }

    #[test]
    fn merge_is_idempotent() {
        let base = json!({ "a": [1, 2], "b": { "c": 1 } });
        let user = json!({ "a": [2, 3], "b": { "d": 2 } });
        let once = merge_profile(base.clone(), &user);
        let twice = merge_profile(once.clone(), &user);
        assert_eq!(once, twice);
        assert_eq!(once, json!({ "a": [1, 2, 3], "b": { "c": 1, "d": 2 } }));
    }

    /// #118: what `nono setup --check-only` prints decides the start-up
    /// warning; anything it does not say plainly is no warning at all.
    #[test]
    fn signal_scoping_is_read_from_the_landlock_abi_nono_reports() {
        let report = |abi: &str| {
            format!(
                "[2/4] Testing sandbox support...\n  * Kernel version: 6.1.0\n  * Landlock enabled (syscall probe)\n  * {abi}\n  * Available features:\n"
            )
        };
        assert_eq!(landlock_abi(&report("Landlock V6")), Some(6));
        assert_eq!(landlock_abi(&report("Landlock V7")), Some(7));
        assert_eq!(landlock_abi(&report("Landlock V5")), Some(5));
        assert_eq!(landlock_abi("Landlock enabled (syscall probe)\n"), None);
        assert_eq!(landlock_abi(""), None);

        assert_eq!(signal_scoping_warning(Some(6)), None);
        assert_eq!(signal_scoping_warning(Some(7)), None);
        assert_eq!(
            signal_scoping_warning(None),
            None,
            "unknown is not a warning"
        );
        assert_eq!(
            signal_scoping_warning(Some(5)).as_deref(),
            Some(
                "Landlock ABI v5 cannot scope signals (v6, Linux 6.12, can): agents' signal_mode \
                 isolated is not enforced, and an agent can signal its supervisor (#118)"
            )
        );
    }

    /// Spec N amendment §4: what the daemon's own git in a clone may reach.
    #[test]
    fn the_git_profile_reads_only_and_carries_nothing_of_the_users() {
        let layout = StateLayout::from_env(Path::new("/h"), |_| None);
        let id: AgentId = "f/c/a".parse().unwrap();
        let paths = layout.agent(&id);
        let crew = layout.crew(&id.crew_ref());
        let git = Path::new("/opt/git/bin/git");
        let exec_path = Path::new("/opt/git/libexec/git-core");
        let p = render_git_profile(&id, &paths, &crew, git, exec_path, &[]);

        assert_eq!(p["meta"]["name"], "balerix-git-f-c-a");
        let fs = p["filesystem"].as_object().unwrap();
        assert_eq!(
            fs.keys().collect::<Vec<_>>(),
            ["read"],
            "no allow, no write: the daemon's git never writes the clone"
        );
        assert_eq!(p["workdir"]["access"], "none");
        assert_eq!(p["network"], json!({ "block": true }));
        assert_eq!(p["environment"]["deny_vars"], json!(["*"]));
        assert_eq!(
            p["environment"]["set_vars"],
            json!({
                "GIT_CEILING_DIRECTORIES": paths.root.display().to_string(),
                "GIT_CONFIG_NOSYSTEM": "1",
                "GIT_NO_LAZY_FETCH": "1",
                "GIT_OPTIONAL_LOCKS": "0",
                "GIT_TERMINAL_PROMPT": "0",
            })
        );

        // a subset of what the agent itself can read, plus the empty
        // hooks directory, the git binary and git's exec-path
        let agent = balerix_grants(
            &id,
            &paths,
            &crew,
            &layout,
            Path::new("/opt/balerix"),
            Path::new("/opt/mise"),
        );
        let read: Vec<PathBuf> = p["filesystem"]["read"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| PathBuf::from(v.as_str().unwrap()))
            .collect();
        for path in &read {
            assert!(
                agent.read.contains(path)
                    || agent.allow.contains(path)
                    || *path == crew.no_hooks()
                    || path == git
                    || path == exec_path,
                "{} is not something the agent can read",
                path.display()
            );
        }
        assert!(read.contains(&paths.workspace));
        assert!(read.contains(&crew.cache_objects()));
        assert!(
            read.contains(&exec_path.to_path_buf()),
            "upload-pack spawns pack-objects through git's exec-path (#109)"
        );
        assert!(!read.contains(&paths.home), "the agent's home is not git's");

        // #111: the daemon's read-only prefixes, and nothing else, join it
        let with = render_git_profile(
            &id,
            &paths,
            &crew,
            git,
            exec_path,
            &[PathBuf::from("/nix/store")],
        );
        let mut expected = p["filesystem"]["read"].as_array().unwrap().clone();
        expected.insert(7, json!("/nix/store")); // after git's own grants
        assert_eq!(with["filesystem"]["read"], Value::Array(expected));
        assert_eq!(with["environment"], p["environment"]);
        assert_eq!(with["network"], p["network"]);
    }

    /// A real tree: the three roots, a plugin's grants under them, and
    /// another plugin beside it (#2).
    struct Reserved {
        _dir: tempfile::TempDir,
        top: PathBuf,
        layout: StateLayout,
        inside: Vec<PathBuf>,
    }

    impl Reserved {
        fn new() -> Self {
            let dir = tempfile::tempdir().unwrap();
            let top = std::fs::canonicalize(dir.path()).unwrap();
            let layout = StateLayout::xdg(top.join("state"), top.join("data"), top.join("config"));
            let web = layout.plugin(&"web".parse().unwrap());
            let package = layout.plugins_data_dir().join("web").join("0123456789ab");
            for d in [
                &web.home,
                &web.scratch,
                &web.kv,
                &package,
                &layout.config_root,
            ] {
                std::fs::create_dir_all(d).unwrap();
            }
            std::fs::create_dir_all(layout.plugin(&"other".parse().unwrap()).home).unwrap();
            let inside = vec![
                package,
                web.home.clone(),
                web.scratch.clone(),
                layout.mise_data_dir(),
            ];
            Self {
                _dir: dir,
                top,
                layout,
                inside,
            }
        }

        fn check(&self, user: Value) -> Result<(), MaterializeError> {
            let id: AgentId = "balerix/plugins/web".parse().unwrap();
            let l = &self.layout;
            let roots: [(&str, &Path); 3] = [
                ("state", &l.state_root),
                ("data", &l.data_root),
                ("config", &l.config_root),
            ];
            let read_only = [self.inside[0].clone(), self.inside[3].clone()];
            let read_write = [self.inside[1].clone(), self.inside[2].clone()];
            check_plugin_sandbox(
                &id,
                &user,
                &roots,
                PluginGrants {
                    read_only: &read_only,
                    read_write: &read_write,
                },
            )
        }

        fn refused(&self, user: Value) -> String {
            let e = self.check(user).unwrap_err();
            assert!(
                matches!(e, MaterializeError::SandboxConflict { .. }),
                "{e:?}"
            );
            e.to_string()
                .replace(&self.top.display().to_string(), "<top>")
        }
    }

    fn read(p: impl AsRef<Path>) -> Value {
        json!({ "filesystem": { "read": [p.as_ref().display().to_string()] } })
    }

    #[test]
    fn a_plugin_cannot_grant_itself_balerixs_own_roots() {
        let r = Reserved::new();
        let id = "balerix/plugins/web";
        assert_eq!(
            r.refused(read(r.layout.server_dir())),
            format!(
                "{id}: sandbox.filesystem.read[0]: <top>/state/server is inside balerix's \
                 state root <top>/state; a plugin may name only paths in its home/ or \
                 scratch/ there, or read its package or the mise pool"
            )
        );
        // another plugin's tree, and its own `kv/`
        let other = r.layout.plugin(&"other".parse().unwrap()).home;
        assert!(
            r.refused(read(&other))
                .contains("inside balerix's state root")
        );
        let kv = r.layout.plugin(&"web".parse().unwrap()).kv;
        assert!(r.refused(read(&kv)).contains("inside balerix's state root"));
        assert!(
            r.refused(read(r.layout.plugins_data_dir().join("other")))
                .contains("inside balerix's data root")
        );
        assert!(
            r.refused(read(r.layout.config_root.join("config.toml")))
                .contains("inside balerix's config root")
        );
        // an ancestor of a root reaches it too
        assert_eq!(
            r.refused(json!({ "filesystem": { "allow": ["/"] } })),
            format!("{id}: sandbox.filesystem.allow[0]: / covers balerix's state root <top>/state")
        );
        assert!(
            r.refused(read(&r.top))
                .contains("covers balerix's state root")
        );
    }

    #[test]
    fn every_grant_list_and_platform_override_is_walked() {
        let r = Reserved::new();
        let server = r.layout.server_dir().display().to_string();
        for key in [
            "read",
            "allow",
            "write",
            "read_file",
            "allow_file",
            "write_file",
        ] {
            let e = r.refused(json!({ "filesystem": { key: ["/opt/ok", server] } }));
            assert!(e.contains(&format!("sandbox.filesystem.{key}[1]: ")), "{e}");
        }
        let e = r.refused(json!({
            "platform_overrides": { "linux": { "filesystem": { "read": [{ "path": server }] } } }
        }));
        assert!(
            e.contains("sandbox.platform_overrides.linux.filesystem.read[0]: "),
            "{e}"
        );
        // keys that grant nothing are not paths
        r.check(json!({ "filesystem": { "deny": [server] } }))
            .unwrap();
    }

    #[test]
    fn paths_must_be_literal_and_absolute() {
        let r = Reserved::new();
        let pkg = r.inside[0].display().to_string();
        for (entry, why) in [
            ("~/.local/state/balerix", "`~` is not expanded"),
            ("$HOME/x", "variables are not expanded"),
            ("/opt/${X}", "variables are not expanded"),
            ("relative/dir", "must be an absolute path"),
            (&format!("{pkg}/../../other"), "must not contain `..`"),
            ("/opt/../etc", "must not contain `..`"),
        ] {
            let e = r.refused(json!({ "filesystem": { "read": [entry] } }));
            assert!(e.contains(why), "{entry}: {e}");
        }
    }

    #[test]
    fn a_symlink_into_a_root_is_refused_by_where_it_leads() {
        let r = Reserved::new();
        let outside = r.top.join("outside");
        std::fs::create_dir_all(&outside).unwrap();
        std::fs::create_dir_all(r.layout.server_dir()).unwrap();
        let link = outside.join("link");
        std::os::unix::fs::symlink(r.layout.server_dir(), &link).unwrap();
        assert!(
            r.refused(read(&link))
                .contains("inside balerix's state root"),
            "the link itself"
        );
        assert!(
            r.refused(read(link.join("token")))
                .contains("inside balerix's state root"),
            "a path that does not exist yet, beneath it"
        );
        // dangling: its target does not exist yet; relative, through `..`
        let dangling = outside.join("dangling");
        std::os::unix::fs::symlink("../state/managed/x", &dangling).unwrap();
        assert!(
            r.refused(read(&dangling))
                .contains("inside balerix's state root"),
            "a dangling link is followed to where it would lead"
        );
        // planted in the plugin's own home, pointing out of it
        let home = &r.inside[1];
        std::os::unix::fs::symlink(r.layout.fleets_dir(), home.join("fleets")).unwrap();
        assert!(
            r.refused(read(home.join("fleets")))
                .contains("inside balerix's state root"),
            "inside a grant as written, not as resolved"
        );
        // and a root reached through a symlinked ancestor of it
        let alias = r.top.join("alias");
        std::os::unix::fs::symlink(&r.top, &alias).unwrap();
        assert!(
            r.refused(read(alias.join("state")))
                .contains("covers balerix's state root")
        );
    }

    #[test]
    fn the_plugins_own_grants_and_unrelated_paths_pass() {
        let r = Reserved::new();
        for p in &r.inside {
            r.check(read(p.join("sub/file"))).unwrap();
            r.check(read(p)).unwrap();
        }
        r.check(json!({
            "filesystem": { "read": ["/opt/data", { "path": "/srv/x" }], "allow": ["/var/tmp/p"] },
            "platform_overrides": { "macos": { "filesystem": { "read": ["/Library/X"] } } },
            "network": { "block": true }
        }))
        .unwrap();
        r.check(json!({})).unwrap();
        r.check(Value::Null).unwrap();
    }

    /// nono expands `*` and `**` in grant paths (0.79.0), so a pattern
    /// would reach a root the literal comparison never saw.
    #[test]
    fn glob_patterns_are_refused_in_every_path_list() {
        let r = Reserved::new();
        let top = r.top.display().to_string();
        for entry in [
            format!("{top}/st*/**"),
            format!("{top}/state/*"),
            "/home/*/.local/state/balerix/**".to_string(),
            "/opt/data?".to_string(),
            "/opt/[ab]".to_string(),
            "/opt/{a,b}".to_string(),
        ] {
            for key in ["read", "allow_file", "deny"] {
                let e = r.refused(json!({ "filesystem": { key: [entry] } }));
                assert!(
                    e.contains("glob patterns (`*`, `?`, `[`, `{`) are not accepted"),
                    "{key} {entry}: {e}"
                );
            }
        }
        let e = r.refused(json!({
            "platform_overrides": { "linux": { "filesystem": { "read": [format!("{top}/st*/**")] } } }
        }));
        assert!(
            e.contains("sandbox.platform_overrides.linux.filesystem.read[0]: "),
            "{e}"
        );
    }

    /// Only `filesystem`, `network` and `security` (and per-OS patches of
    /// them) are a plugin's: every other key nono accepts reaches past
    /// the filesystem rules (`command_policies.commands.<cmd>.sandbox.fs_read`
    /// read the daemon token).
    #[test]
    fn keys_outside_the_plugin_allowlist_are_refused_by_path() {
        let r = Reserved::new();
        let server = r.layout.server_dir().display().to_string();
        let refused = [
            (json!({ "extends": "default" }), "extends"),
            (json!({ "groups": { "include": ["x"] } }), "groups"),
            (json!({ "packs": ["a/b"] }), "packs"),
            (json!({ "workdir": { "access": "readwrite" } }), "workdir"),
            (json!({ "hooks": {} }), "hooks"),
            (json!({ "session_hooks": {} }), "session_hooks"),
            (json!({ "credential_capture": {} }), "credential_capture"),
            (
                json!({ "credential_providers": {} }),
                "credential_providers",
            ),
            (
                json!({ "unsafe_macos_seatbelt_rules": ["(allow default)"] }),
                "unsafe_macos_seatbelt_rules",
            ),
            (
                json!({ "command_policies": { "commands": { "cat": { "sandbox": { "fs_read": [server] } } } } }),
                "command_policies",
            ),
            (json!({ "commands": {} }), "commands"),
            (json!({ "binary": "/bin/sh" }), "binary"),
            (
                json!({ "filesystem": { "unix_socket": ["/run/x.sock"] } }),
                "filesystem.unix_socket",
            ),
            (
                json!({ "filesystem": { "unix_socket_subtree_bind": ["/run"] } }),
                "filesystem.unix_socket_subtree_bind",
            ),
            (
                json!({ "filesystem": { "bypass_protection": ["/x"] } }),
                "filesystem.bypass_protection",
            ),
            (
                json!({ "filesystem": { "suppress_save_prompt": ["/x"] } }),
                "filesystem.suppress_save_prompt",
            ),
            (
                json!({ "network": { "custom_credentials": { "x": { "upstream": "http://127.0.0.1:1", "credential_key": format!("file://{server}/token") } } } }),
                "network.custom_credentials",
            ),
            (
                json!({ "network": { "credentials": ["github"] } }),
                "network.credentials",
            ),
            (
                json!({ "network": { "tls_intercept": {} } }),
                "network.tls_intercept",
            ),
            (
                json!({ "security": { "process_info_mode": "allow_all" } }),
                "security.process_info_mode",
            ),
            (
                json!({ "security": { "capability_elevation": true } }),
                "security.capability_elevation",
            ),
            (
                json!({ "security": { "approval_backends": {} } }),
                "security.approval_backends",
            ),
            (
                json!({ "platform_overrides": { "linux": { "hooks": {} } } }),
                "platform_overrides.linux.hooks",
            ),
            (
                json!({ "platform_overrides": { "linux": { "environment": {} } } }),
                "platform_overrides.linux.environment",
            ),
            (
                json!({ "platform_overrides": { "linux": { "platform_overrides": {} } } }),
                "platform_overrides.linux.platform_overrides",
            ),
            (
                json!({ "platform_overrides": { "beos": {} } }),
                "platform_overrides.beos",
            ),
        ];
        for (block, at) in refused {
            assert_eq!(
                r.refused(block),
                format!(
                    "balerix/plugins/web: sandbox.{at}: not accepted in a plugin's sandbox block"
                )
            );
        }
        assert!(
            r.refused(json!({ "network": [] }))
                .ends_with("sandbox.network: expected an object")
        );
        // `check_conflicts` keeps its own messages for these
        r.check(
            json!({ "environment": {}, "meta": {}, "security": { "signal_mode": "allow_all" } }),
        )
        .unwrap();
    }

    #[test]
    fn a_manifest_using_every_accepted_key_passes() {
        let r = Reserved::new();
        let home = r.inside[1].display().to_string();
        let package = r.inside[0].display().to_string();
        let fs = json!({
            "read": [format!("{package}/lib"), { "path": "/opt/data", "when": "linux" }],
            "read_file": ["/etc/hosts"],
            "allow": [format!("{home}/cache")],
            "allow_file": [format!("{home}/x.db")],
            "write": ["/var/tmp/out"],
            "write_file": ["/var/tmp/out.log"],
            "deny": [r.layout.server_dir().display().to_string()],
        });
        let network = json!({
            "block": false, "allow_http2": true, "network_profile": "dev",
            "allow_domain": ["example.com"], "deny_domain": ["evil.example"],
            "open_port": [8080], "open_port_range": [[9000, 9010]], "connect_port": [443],
            "listen_port": [8081], "listen_port_range": [[9100, 9110]],
            "no_proxy": [".internal"], "upstream_proxy": "proxy:3128", "upstream_bypass": ["*.corp"],
        });
        let security = json!({ "ipc_mode": "full" });
        r.check(json!({
            "filesystem": fs, "network": network, "security": security,
            "platform_overrides": {
                "linux": { "filesystem": fs, "network": network, "security": security },
                "macos": { "filesystem": { "read": ["/Library/X"] } },
                "windows": {},
            }
        }))
        .unwrap();
    }

    /// The package and the pool are read-only grants: a writable entry
    /// inside them is a reach into the root, whatever it resolves to
    /// later (a `home/x` swapped for a link into the pool, say).
    #[test]
    fn an_exemption_holds_only_at_the_level_balerix_grants() {
        let r = Reserved::new();
        let (package, pool) = (&r.inside[0], &r.inside[3]);
        for p in [package, pool] {
            r.check(json!({ "filesystem": { "read": [p.join("x")], "read_file": [p.join("y")] } }))
                .unwrap();
            for key in ["allow", "allow_file", "write", "write_file"] {
                let e = r.refused(json!({ "filesystem": { key: [p.join("x")] } }));
                assert!(e.contains("is inside balerix's data root"), "{key}: {e}");
            }
        }
        // a writable home entry that has become a link into the pool
        std::fs::create_dir_all(pool).unwrap();
        let link = r.inside[1].join("x");
        std::os::unix::fs::symlink(pool, &link).unwrap();
        assert!(
            r.refused(json!({ "filesystem": { "allow": [link] } }))
                .contains("is inside balerix's state root")
        );
        r.check(read(&link)).unwrap();
    }

    /// An entry that is not a nono `ConditionalPath` is refused here, not
    /// skipped and left to nono's validation.
    #[test]
    fn a_path_entry_of_another_shape_is_refused() {
        let r = Reserved::new();
        for entry in [
            json!(42),
            json!(null),
            json!(["/x"]),
            json!({}),
            json!({ "path": 1 }),
            json!({ "path": "/x", "mode": "rw" }),
        ] {
            let e = r.refused(json!({ "filesystem": { "read": ["/ok", entry] } }));
            assert!(
                e.ends_with("sandbox.filesystem.read[1]: expected a path string or { path, when }"),
                "{entry}: {e}"
            );
        }
        r.check(json!({ "filesystem": { "deny": [{ "path": "/x", "when": ["linux"] }] } }))
            .unwrap();
    }
}
