//! The generated nono profile (Phase 2 spec §4.2 step 4, P2-5, P2-7).

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use balerix_core::{AgentId, MaterializeError};
use serde_json::{Value, json};

use crate::fsutil::write_atomic;
use crate::launch::outer_path;
use crate::layout::{AgentPaths, CrewPaths, StateLayout};
use crate::tools::{Cmd, ToolPaths};

pub(crate) const SYSTEM_READ: &[&str] = &["/usr", "/lib", "/lib64", "/bin", "/etc"];

/// Paths balerix grants; user grants that overlap these at a different
/// level are rejected.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Grants {
    pub read: Vec<PathBuf>,
    pub allow: Vec<PathBuf>,
}

pub fn balerix_grants(
    id: &AgentId,
    paths: &AgentPaths,
    crew: &CrewPaths,
    layout: &StateLayout,
    balerix: &Path,
    mise: &Path,
) -> Grants {
    let mut read: Vec<PathBuf> = SYSTEM_READ.iter().map(PathBuf::from).collect();
    // Every pool the agent resolves through: crew, fleet, daemon. All
    // read-only — an agent installs into its own `home/` and can never
    // change a binary a crew-mate executes (Spec E, E-2).
    read.extend(layout.agent_pools(id));
    // `MISE_GLOBAL_CONFIG_FILE` points at the agent's generated `mise.toml`,
    // which sits in the agent root — outside every `allow` below. Without
    // this single-file grant the sandboxed `mise exec` cannot read its own
    // config and dies with "Permission denied (os error 13)".
    read.push(paths.mise_toml.clone());
    // The `SessionStart` relay hook runs this binary inside the sandbox
    // (nono 0.75.0 validates and enforces a single-file `read` entry, and
    // `nono run` inside such a profile executes the granted binary).
    read.push(balerix.to_path_buf());
    // `launch.sh` execs `mise exec` inside the sandbox by the path
    // `ToolPaths` discovered. Locally that is `/usr/local/bin/mise`, inside
    // the `/usr` grant; on a GitHub runner mise-action installs it under
    // `$HOME`, which nothing above grants, and every agent died with exit
    // 127 (command not found). Grant the binary itself; the canonical path
    // in case PATH found a symlink, since Landlock rules bind to the file
    // the path resolves to.
    read.push(std::fs::canonicalize(mise).unwrap_or_else(|_| mise.to_path_buf()));
    // Spec N-3: the crew's object cache, read-only. The agent's private
    // clone borrows objects from it through `objects/info/alternates`; a
    // Landlock read rule on the directory covers the tree beneath it. No
    // path under `repo/` is ever in `allow` — that is the isolation between
    // the agents of one crew (docs/THREAT-MODEL.md).
    read.push(crew.cache_objects());
    Grants {
        read,
        allow: vec![paths.home.clone(), paths.workspace.clone()],
    }
}

fn strs(paths: &[PathBuf]) -> Value {
    Value::Array(
        paths
            .iter()
            .map(|p| Value::String(p.display().to_string()))
            .collect(),
    )
}

/// Base profile ⊕ user block, conflicts rejected first.
pub fn render_profile(
    id: &AgentId,
    grants: &Grants,
    daemon_port: u16,
    env: &BTreeMap<String, String>,
    user: &Value,
) -> Result<Value, MaterializeError> {
    check_conflicts(id, user, grants)?;
    let base = json!({
        "meta": { "name": format!("balerix-{}-{}-{}", id.fleet, id.crew, id.agent), "description": format!("generated by balerix for {id}") },
        "filesystem": { "read": strs(&grants.read), "allow": strs(&grants.allow) },
        "workdir": { "access": "none" },
        // Loopback to the daemon is always allowed; other network stays at
        // nono's default (allowed) unless the user's `sandbox.network`
        // tightens it (architecture spec: "unrestricted by default").
        // `open_port` is the right primitive: it grants localhost TCP on
        // that port and nothing else. `connect_port` would not do — on
        // Landlock it turns outbound TCP into an allowlist, so an agent
        // could reach the daemon and nothing else, not even DNS or the
        // Anthropic API (probed 2026-09-06 with nono 0.75.0). `open_port`
        // also survives a user `block: true`, so hooks keep flowing when
        // egress is cut off.
        "network": { "open_port": [daemon_port] },
        "environment": { "deny_vars": ["*"], "set_vars": env },
        // Written, not left to nono's default: the agent supervisor sits
        // outside the sandbox as the same user, and an agent that could
        // signal it would orphan its own tree out of `stop`'s reach
        // (Spec N amendment §13.6, #118). The top-level key beats a
        // profile the user block `extends`, but nono applies the parent's
        // `platform_overrides` for the running OS after that, so the
        // per-OS patches pin it too. The key is refused in the user block
        // at both levels (`check_conflicts`).
        "security": { "signal_mode": "isolated" },
        "platform_overrides": {
            "linux": { "security": { "signal_mode": "isolated" } },
            "macos": { "security": { "signal_mode": "isolated" } },
        },
    });
    Ok(merge_profile(base, user))
}

/// The profile the daemon's own git runs under in an agent's existing
/// clone: the harvest's `upload-pack` and the probes around it (Spec N
/// amendment 2026-10-01 §4, #68, #70). The daemon reads every repository
/// its uid can; the agent reads its own clone and the crew cache. Under
/// this profile git reads exactly those two (plus the empty hooks
/// directory, its own binary and its exec-path), writes nothing and
/// has no network, so
/// a clone pointed at another repository serves nothing the agent could
/// not already read, and a promisor remote fetches nothing on any git.
///
/// Not derived from the agent's profile: that one carries write access,
/// open network, the user's `sandbox` block and the agent's `env`, none
/// of which the daemon's git should have. `set_vars` holds the hardening
/// for git's environment, since nono drops every variable this list does
/// not name. `git` comes from the host:
/// the binary is granted as a single file, canonical since Landlock rules
/// bind to what the path resolves to, and `exec_path` (`git_exec_path`)
/// as a directory, since `upload-pack` spawns `pack-objects` through it
/// (#109). Its libraries are not granted: a git that loads them from
/// outside `SYSTEM_READ` (nix, Linuxbrew), or a mise shim, cannot run
/// under this profile and the calls fail closed (Spec N amendment §12.1,
/// NS-6) unless the operator names their prefix in the daemon's
/// `[sandbox] git_read` (#111), which `git_read` carries.
pub fn render_git_profile(
    id: &AgentId,
    paths: &AgentPaths,
    crew: &CrewPaths,
    git: &Path,
    exec_path: &Path,
    git_read: &[PathBuf],
) -> Value {
    let mut read: Vec<PathBuf> = SYSTEM_READ.iter().map(PathBuf::from).collect();
    read.push(std::fs::canonicalize(git).unwrap_or_else(|_| git.to_path_buf()));
    read.push(exec_path.to_path_buf());
    // the daemon's `[sandbox] git_read` (config.toml, #111): read-only
    // prefixes a git built outside the system prefixes loads its libraries
    // from; validated at load, never from a fleet's `sandbox` block
    read.extend(git_read.iter().cloned());
    read.push(crew.cache_objects());
    read.push(crew.no_hooks());
    read.push(paths.workspace.clone());
    // git only honours a ceiling that matches the resolved path
    let ceiling = paths
        .root
        .canonicalize()
        .unwrap_or_else(|_| paths.root.clone());
    json!({
        "meta": {
            "name": format!("balerix-git-{}-{}-{}", id.fleet, id.crew, id.agent),
            "description": format!("generated by balerix for its own git in {id}'s clone"),
        },
        "filesystem": { "read": strs(&read) },
        "workdir": { "access": "none" },
        "network": { "block": true },
        "environment": {
            "deny_vars": ["*"],
            "set_vars": {
                "GIT_OPTIONAL_LOCKS": "0",
                "GIT_NO_LAZY_FETCH": "1",
                "GIT_TERMINAL_PROMPT": "0",
                "GIT_CONFIG_NOSYSTEM": "1",
                "GIT_CEILING_DIRECTORIES": ceiling.display().to_string(),
            },
        },
    })
}

/// The directory the host git runs its helpers from, resolved. Asked of
/// git itself, unsandboxed: it names no repository and reads nothing the
/// agent wrote. From an empty environment but `PATH`, as the sandboxed
/// call starts: a `GIT_EXEC_PATH` the daemon inherited would make the
/// grant name a directory the sandboxed git never uses. A git that
/// cannot answer, or names something that is not a directory, fails the
/// step: no profile is written without the grant.
fn git_exec_path(tools: &ToolPaths, id: &str) -> Result<PathBuf, MaterializeError> {
    let tool_error = |stderr: String| MaterializeError::Tool {
        id: id.to_string(),
        tool: "git".into(),
        subcommand: "--exec-path".into(),
        args: vec!["--exec-path".into()],
        stderr,
    };
    let out = Cmd::new(&tools.git)
        .env_clear()
        .env("PATH", outer_path(tools))
        .args(["--exec-path"])
        .run()
        .map_err(|f| tool_error(f.stderr))?;
    let named = PathBuf::from(out.stdout.trim_end_matches(['\r', '\n']));
    let dir = std::fs::canonicalize(&named)
        .map_err(|e| tool_error(format!("{}: {e}", named.display())))?;
    if !dir.is_dir() {
        return Err(tool_error(format!("{}: not a directory", named.display())));
    }
    Ok(dir)
}

/// Writes the git profile just before the daemon uses it, so nothing
/// depends on the order of the materialize steps or on a file an earlier
/// pass (or anything else) left there. Validated only when the bytes
/// changed. Creates what nono needs to exist: the hooks directory the
/// profile names, nono's `$HOME` and the log directory.
pub fn write_git_profile(
    tools: &ToolPaths,
    id: &str,
    paths: &AgentPaths,
    crew: &CrewPaths,
    git_read: &[PathBuf],
) -> Result<(), MaterializeError> {
    let agent_id: AgentId = id.parse().map_err(|_| MaterializeError::Invalid {
        id: id.to_string(),
        message: "not an agent id".into(),
    })?;
    for dir in [crew.no_hooks(), paths.nono_home.clone(), paths.logs.clone()] {
        std::fs::create_dir_all(&dir).map_err(|e| MaterializeError::Io {
            id: id.to_string(),
            path: dir.clone(),
            message: e.to_string(),
        })?;
    }
    let exec_path = git_exec_path(tools, id)?;
    let profile = render_git_profile(&agent_id, paths, crew, &tools.git, &exec_path, git_read);
    let path = paths.git_profile.clone();
    if write_profile_at(&agent_id, &path, &profile)? {
        // nono's state stays out of the agent's own `nono/` (#108)
        let home = crate::workspace::ScratchHome::new(paths).map_err(|e| MaterializeError::Io {
            id: id.to_string(),
            path: paths.nono_home.clone(),
            message: format!("cannot create nono's home beside it: {e}"),
        })?;
        validate_profile_at(
            tools,
            &agent_id,
            &path,
            home.path(),
            &paths.logs.join("nono.validate.log"),
        )?;
    }
    Ok(())
}

/// nono's `extends` rules: arrays append and dedupe, maps recurse, scalars
/// user-wins.
pub fn merge_profile(base: Value, user: &Value) -> Value {
    match (base, user) {
        (Value::Object(mut b), Value::Object(u)) => {
            for (k, v) in u {
                let merged = match b.remove(k) {
                    Some(existing) => merge_profile(existing, v),
                    None => v.clone(),
                };
                b.insert(k.clone(), merged);
            }
            Value::Object(b)
        }
        (Value::Array(mut b), Value::Array(u)) => {
            for v in u {
                if !b.contains(v) {
                    b.push(v.clone());
                }
            }
            Value::Array(b)
        }
        (_, u) => u.clone(),
    }
}

/// Access level of a grant list key.
fn level(key: &str) -> Option<&'static str> {
    match key {
        "read" | "read_file" => Some("read"),
        "allow" | "allow_file" => Some("allow"),
        "write" | "write_file" => Some("write"),
        _ => None,
    }
}

fn overlaps(a: &Path, b: &Path) -> bool {
    a == b || a.starts_with(b) || b.starts_with(a)
}

fn entry_path(v: &Value) -> Option<PathBuf> {
    match v {
        Value::String(s) => Some(PathBuf::from(s)),
        Value::Object(m) => m.get("path").and_then(Value::as_str).map(PathBuf::from),
        _ => None,
    }
}

pub fn check_conflicts(
    id: &AgentId,
    user: &Value,
    grants: &Grants,
) -> Result<(), MaterializeError> {
    let conflict = |path: String, message: String| MaterializeError::SandboxConflict {
        id: id.to_string(),
        path,
        message,
    };
    let Value::Object(u) = user else {
        return Ok(());
    };
    if u.contains_key("environment") {
        return Err(conflict(
            "environment".into(),
            "balerix-owned; set variables through `env` instead".into(),
        ));
    }
    if u.contains_key("meta") {
        return Err(conflict("meta".into(), "balerix-owned".into()));
    }
    check_security(u, "", &conflict)?;
    if let Some(overrides) = u.get("platform_overrides") {
        let Value::Object(os) = overrides else {
            return Err(conflict(
                "platform_overrides".into(),
                "expected an object".into(),
            ));
        };
        // nono applies the patch for the running OS after `extends`, so
        // it could loosen what the base profile pins
        for (name, patch) in os {
            if let Value::Object(patch) = patch {
                check_security(patch, &format!("platform_overrides.{name}."), &conflict)?;
            }
        }
    }
    let Some(fs_value) = u.get("filesystem") else {
        return Ok(());
    };
    let Value::Object(fs) = fs_value else {
        return Err(conflict("filesystem".into(), "expected an object".into()));
    };
    for (key, entries) in fs {
        let Some(user_level) = level(key) else {
            continue;
        };
        let Value::Array(items) = entries else {
            return Err(conflict(
                format!("filesystem.{key}"),
                "expected an array".into(),
            ));
        };
        for (i, item) in items.iter().enumerate() {
            let Some(p) = entry_path(item) else {
                continue;
            };
            let hits = grants
                .read
                .iter()
                .map(|g| (g, "read"))
                .chain(grants.allow.iter().map(|g| (g, "allow")));
            for (g, balerix_level) in hits {
                if overlaps(&p, g) && balerix_level != user_level {
                    return Err(conflict(
                        format!("filesystem.{key}[{i}]"),
                        format!(
                            "{} overlaps balerix {balerix_level} path {}",
                            p.display(),
                            g.display()
                        ),
                    ));
                }
            }
        }
    }
    Ok(())
}

/// `security.signal_mode` is balerix's (#118), whatever its value: even
/// `null` hands the decision to whatever profile `extends` names. The rest
/// of `security` is the user's.
fn check_security(
    block: &serde_json::Map<String, Value>,
    prefix: &str,
    conflict: &impl Fn(String, String) -> MaterializeError,
) -> Result<(), MaterializeError> {
    let Some(security) = block.get("security") else {
        return Ok(());
    };
    let Value::Object(security) = security else {
        return Err(conflict(
            format!("{prefix}security"),
            "expected an object".into(),
        ));
    };
    if security.contains_key("signal_mode") {
        return Err(conflict(
            format!("{prefix}security.signal_mode"),
            "balerix-owned; agents stay signal-isolated".into(),
        ));
    }
    Ok(())
}

/// Writes the profile; returns whether its bytes changed.
pub fn write_profile_at(
    id: &AgentId,
    path: &Path,
    profile: &Value,
) -> Result<bool, MaterializeError> {
    let bytes = serde_json::to_vec_pretty(profile).unwrap_or_default();
    if std::fs::read(path).ok().as_deref() == Some(bytes.as_slice()) {
        return Ok(false);
    }
    // 0600: the profile is the sandbox's boundary, and a writable or
    // widely readable one is a map of every path the agent may reach.
    write_atomic(path, &bytes, 0o600).map_err(|e| MaterializeError::Io {
        id: id.to_string(),
        path: path.to_path_buf(),
        message: e.to_string(),
    })?;
    Ok(true)
}

pub fn write_profile(
    id: &AgentId,
    paths: &AgentPaths,
    profile: &Value,
) -> Result<bool, MaterializeError> {
    write_profile_at(id, &paths.profile, profile)
}

pub fn validate_profile_at(
    tools: &ToolPaths,
    id: &AgentId,
    profile: &Path,
    nono_home: &Path,
    log: &Path,
) -> Result<(), MaterializeError> {
    Cmd::new(&tools.nono)
        .args(["-s", "profile", "validate", &profile.display().to_string()])
        .env("HOME", nono_home.display().to_string())
        .log(log)
        .run()
        .map(|_| ())
        .map_err(|f| MaterializeError::Tool {
            id: id.to_string(),
            tool: f.tool,
            subcommand: "profile validate".into(),
            args: f.args,
            stderr: if f.stderr.trim().is_empty() {
                "profile invalid".into()
            } else {
                f.stderr
            },
        })
}

pub fn validate_profile(
    tools: &ToolPaths,
    id: &AgentId,
    paths: &AgentPaths,
) -> Result<(), MaterializeError> {
    validate_profile_at(
        tools,
        id,
        &paths.profile,
        &paths.nono_home,
        &paths.logs.join("nono.validate.log"),
    )
}

/// Spec O §6.2 step 2: `nono -s run --profile <profile> -- /bin/true` in
/// the sidecar's own container, which shares the pod's seccomp settings
/// and the node's kernel with the agent container. nono's own exit 1 with
/// `Landlock not available` is the `SandboxUnavailable` signal (§19.2);
/// `/sys/kernel/security/lsm` is not mounted in a pod, so there is nothing
/// else to read.
pub fn sandbox_self_test(tools: &ToolPaths, paths: &AgentPaths) -> Result<(), SelfTestError> {
    let out = std::process::Command::new(&tools.nono)
        .args(["-s", "run", "--profile"])
        .arg(&paths.profile)
        .args(["--", "/bin/true"])
        .env_clear()
        .env("HOME", &paths.nono_home)
        .env("PATH", "/usr/local/bin:/usr/bin:/bin")
        .output()
        .map_err(|e| SelfTestError::Io(e.to_string()))?;
    if out.status.success() {
        return Ok(());
    }
    let stderr = String::from_utf8_lossy(&out.stderr);
    let line = stderr.lines().next().unwrap_or("").trim().to_string();
    if out.status.code() == Some(1) && line.contains("Landlock not available") {
        return Err(SelfTestError::Unavailable(line));
    }
    Err(SelfTestError::Failed(line))
}

/// The Landlock ABI that scopes signals (Linux 6.12). Below it nono
/// cannot enforce `signal_mode: isolated` (#118).
pub const SIGNAL_SCOPING_ABI: u32 = 6;

/// The ABI `nono setup --check-only` reports on its `Landlock V<n>` line;
/// `None` when no such line is there.
pub fn landlock_abi(setup_report: &str) -> Option<u32> {
    setup_report.lines().find_map(|line| {
        line.trim()
            .trim_start_matches(['*', ' '])
            .strip_prefix("Landlock V")?
            .trim()
            .parse()
            .ok()
    })
}

/// The start-up warning for a kernel that cannot scope signals, if any.
/// An unknown ABI warns about nothing: the serve start-up never fails on
/// this, and a guess is no better than silence.
pub fn signal_scoping_warning(abi: Option<u32>) -> Option<String> {
    let abi = abi?;
    (abi < SIGNAL_SCOPING_ABI).then(|| {
        format!(
            "Landlock ABI v{abi} cannot scope signals (v{SIGNAL_SCOPING_ABI}, Linux 6.12, can): \
             agents' signal_mode isolated is not enforced, and an agent can signal its \
             supervisor (#118)"
        )
    })
}

/// Asks `nono setup --check-only` for the kernel's Landlock ABI, from an
/// empty environment with `home` as nono's `$HOME`; with its update check
/// off it writes nothing there. `None` when nono cannot be run or does
/// not say.
pub fn host_landlock_abi(tools: &ToolPaths, home: &Path) -> Option<u32> {
    let out = std::process::Command::new(&tools.nono)
        .args(["setup", "--check-only"])
        .env_clear()
        .env("HOME", home)
        .env("PATH", "/usr/local/bin:/usr/bin:/bin")
        .env("NO_COLOR", "1")
        // otherwise it asks update.nono.sh and records that under `home`
        .env("NONO_NO_UPDATE_CHECK", "1")
        .output()
        .ok()?;
    landlock_abi(&String::from_utf8_lossy(&out.stdout))
        .or_else(|| landlock_abi(&String::from_utf8_lossy(&out.stderr)))
}

#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum SelfTestError {
    /// nono exited 1 with `Landlock not available` (Spec O §19.2).
    #[error("SandboxUnavailable: {0}")]
    Unavailable(String),
    /// Any other non-zero exit; the first stderr line.
    #[error("sandbox self-test failed: {0}")]
    Failed(String),
    #[error("sandbox self-test could not run nono: {0}")]
    Io(String),
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fixture() -> (AgentId, Grants, BTreeMap<String, String>) {
        let layout = StateLayout::from_env(Path::new("/h"), |_| None);
        let id: AgentId = "f/c/a".parse().unwrap();
        let paths = layout.agent(&id);
        let crew = layout.crew(&id.crew_ref());
        let grants = balerix_grants(
            &id,
            &paths,
            &crew,
            &layout,
            Path::new("/opt/balerix"),
            Path::new("/opt/mise"),
        );
        (
            id,
            grants,
            BTreeMap::from([("HOME".to_string(), paths.home.display().to_string())]),
        )
    }

    #[test]
    fn base_profile_has_the_required_grants_env_and_port() {
        let (id, grants, env) = fixture();
        let p = render_profile(&id, &grants, 7643, &env, &json!({})).unwrap();
        assert_eq!(p["meta"]["name"], "balerix-f-c-a");
        assert_eq!(p["filesystem"]["read"][0], "/usr");
        assert_eq!(
            p["filesystem"]["read"][5], "/h/.local/state/balerix/fleets/f/crews/c/mise",
            "crew pool"
        );
        assert_eq!(
            p["filesystem"]["read"][6], "/h/.local/state/balerix/fleets/f/mise",
            "fleet pool"
        );
        assert_eq!(
            p["filesystem"]["read"][7], "/h/.local/share/balerix/mise",
            "daemon pool"
        );
        assert_eq!(
            p["filesystem"]["read"][8],
            "/h/.local/state/balerix/fleets/f/crews/c/agents/a/mise.toml"
        );
        assert_eq!(p["filesystem"]["read"][9], "/opt/balerix");
        assert_eq!(
            p["filesystem"]["read"][10], "/opt/mise",
            "mise may live outside /usr (CI installs it under $HOME)"
        );
        assert_eq!(
            p["filesystem"]["read"][11],
            "/h/.local/state/balerix/fleets/f/crews/c/repo/.git/objects",
            "Spec N-3: the crew's object cache, read-only"
        );
        assert_eq!(p["filesystem"]["read"].as_array().unwrap().len(), 12);
        assert_eq!(
            p["filesystem"]["allow"],
            json!([
                "/h/.local/state/balerix/fleets/f/crews/c/agents/a/home",
                "/h/.local/state/balerix/fleets/f/crews/c/agents/a/workspace",
            ]),
            "nothing under crews/c/repo is ever writable (Spec N §6)"
        );
        assert_eq!(p["workdir"]["access"], "none");
        assert_eq!(
            p["security"],
            json!({ "signal_mode": "isolated" }),
            "pinned, not left to nono's default: the supervisor outside must not be signalled (#118)"
        );
        assert_eq!(
            p["platform_overrides"],
            json!({
                "linux": { "security": { "signal_mode": "isolated" } },
                "macos": { "security": { "signal_mode": "isolated" } },
            }),
            "an `extends` parent's per-OS override is applied after the top level"
        );
        assert_eq!(
            p["network"],
            json!({ "open_port": [7643] }),
            "loopback to the daemon only; no connect_port allowlist"
        );
        assert_eq!(p["environment"]["deny_vars"], json!(["*"]));
        assert_eq!(
            p["environment"]["set_vars"]["HOME"],
            "/h/.local/state/balerix/fleets/f/crews/c/agents/a/home"
        );
    }

    #[test]
    fn user_block_merges_with_extends_semantics() {
        let (id, grants, env) = fixture();
        let user = json!({ "network": { "block": true, "open_port": [7643, 8080] }, "filesystem": { "read": ["/opt/data"] }, "extends": "default" });
        let p = render_profile(&id, &grants, 7643, &env, &user).unwrap();
        assert_eq!(p["network"]["block"], true);
        assert_eq!(
            p["network"]["open_port"],
            json!([7643, 8080]),
            "append + dedupe"
        );
        assert_eq!(
            p["filesystem"]["read"].as_array().unwrap().last().unwrap(),
            "/opt/data"
        );
        assert_eq!(p["extends"], "default");
    }

    #[test]
    fn a_user_network_block_keeps_the_daemon_reachable() {
        let (id, grants, env) = fixture();
        let user = json!({ "network": { "block": true } });
        let p = render_profile(&id, &grants, 7643, &env, &user).unwrap();
        assert_eq!(p["network"]["block"], true);
        assert_eq!(
            p["network"]["open_port"],
            json!([7643]),
            "hooks must reach the daemon even when egress is blocked"
        );
        let user = json!({ "network": { "connect_port": [443] } });
        let p = render_profile(&id, &grants, 7643, &env, &user).unwrap();
        assert_eq!(p["network"]["connect_port"], json!([443]));
        assert_eq!(p["network"]["open_port"], json!([7643]));
    }

    #[test]
    fn owned_keys_and_overlapping_grants_are_rejected_with_paths() {
        let (id, grants, env) = fixture();
        let e = render_profile(
            &id,
            &grants,
            1,
            &env,
            &json!({ "environment": { "set_vars": { "X": "1" } } }),
        )
        .unwrap_err();
        assert_eq!(
            e.to_string(),
            "f/c/a: sandbox.environment: balerix-owned; set variables through `env` instead"
        );
        let e = render_profile(
            &id,
            &grants,
            1,
            &env,
            &json!({ "filesystem": { "read": ["/x", "/h/.local/state/balerix/fleets/f/crews/c/agents/a/home/.claude"] } }),
        )
        .unwrap_err();
        assert_eq!(
            e.to_string(),
            "f/c/a: sandbox.filesystem.read[1]: /h/.local/state/balerix/fleets/f/crews/c/agents/a/home/.claude overlaps balerix allow path /h/.local/state/balerix/fleets/f/crews/c/agents/a/home"
        );
        let e = render_profile(
            &id,
            &grants,
            1,
            &env,
            &json!({ "filesystem": { "allow": [{ "path": "/usr/local" }] } }),
        )
        .unwrap_err();
        assert!(e.to_string().contains("overlaps balerix read path /usr"));
        // same level is fine
        assert!(
            render_profile(
                &id,
                &grants,
                1,
                &env,
                &json!({ "filesystem": { "read": ["/usr/share"] } })
            )
            .is_ok()
        );
    }

    /// #118: the agent must not loosen signal isolation, whether at the
    /// top level or through the per-OS patch nono applies after `extends`.
    #[test]
    fn signal_mode_is_balerix_owned_at_every_level() {
        let (id, grants, env) = fixture();
        let refuse = |user: Value| {
            render_profile(&id, &grants, 1, &env, &user)
                .unwrap_err()
                .to_string()
        };
        assert_eq!(
            refuse(json!({ "security": { "signal_mode": "allow_all" } })),
            "f/c/a: sandbox.security.signal_mode: balerix-owned; agents stay signal-isolated"
        );
        assert_eq!(
            refuse(json!({ "security": { "signal_mode": null } })),
            "f/c/a: sandbox.security.signal_mode: balerix-owned; agents stay signal-isolated",
            "null would fall back to whatever `extends` names"
        );
        assert_eq!(
            refuse(
                json!({ "platform_overrides": { "linux": { "security": { "signal_mode": "allow_same_sandbox" } } } })
            ),
            "f/c/a: sandbox.platform_overrides.linux.security.signal_mode: balerix-owned; agents stay signal-isolated"
        );
        assert_eq!(
            refuse(
                json!({ "platform_overrides": { "macos": { "security": { "signal_mode": "allow_all" } } } })
            ),
            "f/c/a: sandbox.platform_overrides.macos.security.signal_mode: balerix-owned; agents stay signal-isolated"
        );
        assert_eq!(
            refuse(json!({ "security": "allow_all" })),
            "f/c/a: sandbox.security: expected an object"
        );
        assert_eq!(
            refuse(json!({ "platform_overrides": { "linux": { "security": null } } })),
            "f/c/a: sandbox.platform_overrides.linux.security: expected an object"
        );
        // the rest of `security` is the user's
        let p = render_profile(
            &id,
            &grants,
            1,
            &env,
            &json!({ "security": { "process_info_mode": "allow_all" } }),
        )
        .unwrap();
        assert_eq!(
            p["security"],
            json!({ "signal_mode": "isolated", "process_info_mode": "allow_all" })
        );
        assert!(
            render_profile(
                &id,
                &grants,
                1,
                &env,
                &json!({ "platform_overrides": { "linux": { "network": { "block": true } } } })
            )
            .is_ok()
        );
    }

    #[test]
    fn malformed_filesystem_shapes_are_rejected() {
        let (id, grants, env) = fixture();
        let e =
            render_profile(&id, &grants, 1, &env, &json!({ "filesystem": "nope" })).unwrap_err();
        assert_eq!(
            e.to_string(),
            "f/c/a: sandbox.filesystem: expected an object"
        );
        let e = render_profile(
            &id,
            &grants,
            1,
            &env,
            &json!({ "filesystem": { "read": "/opt/data" } }),
        )
        .unwrap_err();
        assert_eq!(
            e.to_string(),
            "f/c/a: sandbox.filesystem.read: expected an array"
        );
    }

    #[test]
    fn every_pool_the_agent_resolves_through_is_readable() {
        let layout = StateLayout::from_env(Path::new("/h"), |_| None);
        let id: AgentId = "payments/backend/alice".parse().unwrap();
        let paths = layout.agent(&id);
        let crew = layout.crew(&id.crew_ref());
        let g = balerix_grants(
            &id,
            &paths,
            &crew,
            &layout,
            Path::new("/tools/balerix"),
            Path::new("/tools/mise"),
        );
        for pool in layout.agent_pools(&id) {
            assert!(
                g.read.contains(&pool),
                "{} must be readable inside the sandbox",
                pool.display()
            );
        }
        for pool in layout.agent_pools(&id) {
            assert!(
                !g.allow.contains(&pool),
                "{} must never be writable",
                pool.display()
            );
        }
    }

    #[test]
    fn merge_is_idempotent() {
        let base = json!({ "a": [1, 2], "b": { "c": 1 } });
        let user = json!({ "a": [2, 3], "b": { "d": 2 } });
        let once = merge_profile(base.clone(), &user);
        let twice = merge_profile(once.clone(), &user);
        assert_eq!(once, twice);
        assert_eq!(once, json!({ "a": [1, 2, 3], "b": { "c": 1, "d": 2 } }));
    }

    /// #118: what `nono setup --check-only` prints decides the start-up
    /// warning; anything it does not say plainly is no warning at all.
    #[test]
    fn signal_scoping_is_read_from_the_landlock_abi_nono_reports() {
        let report = |abi: &str| {
            format!(
                "[2/4] Testing sandbox support...\n  * Kernel version: 6.1.0\n  * Landlock enabled (syscall probe)\n  * {abi}\n  * Available features:\n"
            )
        };
        assert_eq!(landlock_abi(&report("Landlock V6")), Some(6));
        assert_eq!(landlock_abi(&report("Landlock V7")), Some(7));
        assert_eq!(landlock_abi(&report("Landlock V5")), Some(5));
        assert_eq!(landlock_abi("Landlock enabled (syscall probe)\n"), None);
        assert_eq!(landlock_abi(""), None);

        assert_eq!(signal_scoping_warning(Some(6)), None);
        assert_eq!(signal_scoping_warning(Some(7)), None);
        assert_eq!(
            signal_scoping_warning(None),
            None,
            "unknown is not a warning"
        );
        assert_eq!(
            signal_scoping_warning(Some(5)).as_deref(),
            Some(
                "Landlock ABI v5 cannot scope signals (v6, Linux 6.12, can): agents' signal_mode \
                 isolated is not enforced, and an agent can signal its supervisor (#118)"
            )
        );
    }

    /// Spec N amendment §4: what the daemon's own git in a clone may reach.
    #[test]
    fn the_git_profile_reads_only_and_carries_nothing_of_the_users() {
        let layout = StateLayout::from_env(Path::new("/h"), |_| None);
        let id: AgentId = "f/c/a".parse().unwrap();
        let paths = layout.agent(&id);
        let crew = layout.crew(&id.crew_ref());
        let git = Path::new("/opt/git/bin/git");
        let exec_path = Path::new("/opt/git/libexec/git-core");
        let p = render_git_profile(&id, &paths, &crew, git, exec_path, &[]);

        assert_eq!(p["meta"]["name"], "balerix-git-f-c-a");
        let fs = p["filesystem"].as_object().unwrap();
        assert_eq!(
            fs.keys().collect::<Vec<_>>(),
            ["read"],
            "no allow, no write: the daemon's git never writes the clone"
        );
        assert_eq!(p["workdir"]["access"], "none");
        assert_eq!(p["network"], json!({ "block": true }));
        assert_eq!(p["environment"]["deny_vars"], json!(["*"]));
        assert_eq!(
            p["environment"]["set_vars"],
            json!({
                "GIT_CEILING_DIRECTORIES": paths.root.display().to_string(),
                "GIT_CONFIG_NOSYSTEM": "1",
                "GIT_NO_LAZY_FETCH": "1",
                "GIT_OPTIONAL_LOCKS": "0",
                "GIT_TERMINAL_PROMPT": "0",
            })
        );

        // a subset of what the agent itself can read, plus the empty
        // hooks directory, the git binary and git's exec-path
        let agent = balerix_grants(
            &id,
            &paths,
            &crew,
            &layout,
            Path::new("/opt/balerix"),
            Path::new("/opt/mise"),
        );
        let read: Vec<PathBuf> = p["filesystem"]["read"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| PathBuf::from(v.as_str().unwrap()))
            .collect();
        for path in &read {
            assert!(
                agent.read.contains(path)
                    || agent.allow.contains(path)
                    || *path == crew.no_hooks()
                    || path == git
                    || path == exec_path,
                "{} is not something the agent can read",
                path.display()
            );
        }
        assert!(read.contains(&paths.workspace));
        assert!(read.contains(&crew.cache_objects()));
        assert!(
            read.contains(&exec_path.to_path_buf()),
            "upload-pack spawns pack-objects through git's exec-path (#109)"
        );
        assert!(!read.contains(&paths.home), "the agent's home is not git's");

        // #111: the daemon's read-only prefixes, and nothing else, join it
        let with = render_git_profile(
            &id,
            &paths,
            &crew,
            git,
            exec_path,
            &[PathBuf::from("/nix/store")],
        );
        let mut expected = p["filesystem"]["read"].as_array().unwrap().clone();
        expected.insert(7, json!("/nix/store")); // after git's own grants
        assert_eq!(with["filesystem"]["read"], Value::Array(expected));
        assert_eq!(with["environment"], p["environment"]);
        assert_eq!(with["network"], p["network"]);
    }
}
